// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCktpRZa6jgw_J_Uuw8Dz4Q2hapTYw7sM8',
    appId: '1:893050080341:web:895df3880548bd372a58dc',
    messagingSenderId: '893050080341',
    projectId: 'demofirebase-a58d1',
    authDomain: 'demofirebase-a58d1.firebaseapp.com',
    storageBucket: 'demofirebase-a58d1.firebasestorage.app',
    measurementId: 'G-D1XTML9FH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_wwWmzdGCAvF0BgFyZCXPdVLwMEyZVSk',
    appId: '1:893050080341:android:2db665b68bc2fd852a58dc',
    messagingSenderId: '893050080341',
    projectId: 'demofirebase-a58d1',
    storageBucket: 'demofirebase-a58d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVFwN-dDe0uVDbZIHkOaBku1ixjrJusaM',
    appId: '1:893050080341:ios:d21f5c708f774ae92a58dc',
    messagingSenderId: '893050080341',
    projectId: 'demofirebase-a58d1',
    storageBucket: 'demofirebase-a58d1.firebasestorage.app',
    iosBundleId: 'com.example.demoqlct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVFwN-dDe0uVDbZIHkOaBku1ixjrJusaM',
    appId: '1:893050080341:ios:d21f5c708f774ae92a58dc',
    messagingSenderId: '893050080341',
    projectId: 'demofirebase-a58d1',
    storageBucket: 'demofirebase-a58d1.firebasestorage.app',
    iosBundleId: 'com.example.demoqlct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCktpRZa6jgw_J_Uuw8Dz4Q2hapTYw7sM8',
    appId: '1:893050080341:web:c0d014bf5df77fba2a58dc',
    messagingSenderId: '893050080341',
    projectId: 'demofirebase-a58d1',
    authDomain: 'demofirebase-a58d1.firebaseapp.com',
    storageBucket: 'demofirebase-a58d1.firebasestorage.app',
    measurementId: 'G-Q3274FCD5S',
  );
}
